name: UNTITLEDFILES
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38838
title: curated by Radek Sadowski
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e0e0e'
    - '#6b6b6b'
    - '#303030'
    - '#bbbbbb'
  brandStrength: 1
  lightness: 0.4821922436822206
  saturation: 0.8900252850726247
  rhythmicContrast: 0.37211578455753624
purpose: []
